version: "3.8"

services:
  list-server:
    build: .
    container_name: raspi-status-list-server
    ports:
      - "9092"
    volumes:
      - /usr/share/nginx/html:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - internal-net

networks:
  internal-net:
    external: true
